### ISSUE TITLE
NPM package inconsistent with Github

### ISSUE THREAD

**Issue by samueltuckey** [ozum/pg-generator-example#2]
Hey Ozum

It appears the nom package is inconsistent with GitHub commits.

For example package.json -> version is set to  "0.0.0" in GitHub and "1.0.0" when installed via npm.

The build also fails for master.

I also can't get the package working locally unless I pull out v1.0.0-alpha.1

Is there any chance you could either update the code or point me in the correct direction?

Thanks, Sam

**Comment by ozum** [comment]
Hi @samueltuckey,

> It appears the nom package is inconsistent with GitHub commits. For example package.json -> version is set to "0.0.0" in GitHub and "1.0.0" when installed via npm.


This package uses [`semantic-release`](https://semantic-release.gitbook.io/semantic-release), so version numbers of npm packages are automatically assigned by CI. The version number in the GitHub will be always 0.0.0.

> The build also fails for master. I also can't get the package working locally unless I pull out v1.0.0-alpha.1

This package is an example package used by [`pg-generator`](https://www.pg-generator.com) to show you how to prepare your own generators. I assume you use it with `pg-generator` as intended. If so, please see below.

> Is there any chance you could either update the code or point me in the correct direction?

First, install [`pg-generator`](https://www.pg-generator.com) and this package.

`npm install -g pg-generator@5.0.0-alpha.8 pg-generator-example@1.0.0-alpha.2` then follow the instructions on the [`pg-generator`](https://www.pg-generator.com) page.

After you execute and see how this example package works, examine the examples in the `pg-generator-example`. Copy and modify them or create from scratch according to your needs by creating your own package (i.e. `pg-generator-my-orm`).

**Comment by samueltuckey** [comment]
Hi Ozum

Thanks of the help.

It turned out to be a node packaging problem. Once I removed the typedoc packages from package.json, it all compiled and worked properly.


so removed these:
    "typedoc": "^0.20.30",
    "typedoc-neo-theme": "^1.1.0",
    "typedoc-plugin-example-tag": "^1.0.2",
    "typedoc-plugin-markdown": "^3.6.0",
    "typedoc-plugin-param-names": "^2.0.0",
